uint8 	turn_light_left_ctrl #	左转向灯控制		"0：关闭 1：开启       "
uint8 	turn_light_right_ctrl #	右转向灯控制		"0：关闭 1：开启       "
uint8   high_beam #远光灯     "0：关闭 1：开启       "
uint8   low_beam #近光灯     "0：关闭 1：开启       "
int32   turn_angle #转向角
uint8   epsxbw_enable	#方向盘使能 0:停止方向盘线控控制 1:方向盘线控控制
uint8   enter_autodriver #驾驶模式切换: 0:退出自动驾驶模式 1:进入自动驾驶模式
int8 	drv_light_ctrl  #	行车灯控制		"0：关闭  1：开启       "
int8   	horn_ctrl  #	喇叭控制		"0：关闭  1：开启       "
int8   	up_lidar_ctrl  #	顶激光雷达		"0：关闭  1：开启       "
int8   	front_lidar_ctrl  #	前激光雷达		"0：关闭  1：开启       "
int8   	water_meter_ctrl  #	水量档位控制		0~3档水量调节
int8   	brush_pressure_ctrl	 #刷盘压力控制		0~3档压力调节
int8   	speed_level_ctrl  #	速度档位控制		0~3档速度调节
int8   	suction_ctrl  #	吸水马达吸力控制		0~3档压力调节
int8   	sidebrush_state_ctrl  #	边刷状态控制(预留)
int8    scrubbing_instruc  	  # 洗地指令	
