float32 	targetsangle
float32 	targetaccel	
float32 	targetshiftposition
float32     targettorque
float32 	steer_angle	
float32 	realstrtorque	
float32 	shiftlvlposition	
float32 	velocity	
int8 	fault_level #	整车故障等级
int8 	epb_status #	手刹状态
int8 	control_switch_state #	横纵向使能按钮
float32 	vehicle_accel #	车辆加速度
float32 	brake_state #	制动压力
int8        selfdriv_ready
int8        parall_ready
int8        remote_ready
int8 control_emergency  
int8 	control_mode   	# remote_control  self_control etc  emergency_mode
