Class: ""
Displays:
  - Alpha: 0.5
    Cell Size: 10
    Class: rviz/Grid
    Color: 160; 160; 160
    Enabled: true
    Line Style:
      Line Width: 0.0299999993
      Value: Lines
    Name: Grid
    Normal Cell Count: 0
    Offset:
      X: 0
      Y: 0
      Z: 0
    Plane: XY
    Plane Cell Count: 150
    Reference Frame: <Fixed Frame>
    Value: true
  - Class: rviz/Marker
    Enabled: true
    Marker Topic: /ivmotionplanner_text
    Name: speedtext
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Class: rviz/Marker
    Enabled: true
    Marker Topic: /ivmotionplanner_Marker
    Name: motion_path
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Class: rviz/Marker
    Enabled: true
    Marker Topic: /path_visualize
    Name: path
    Namespaces:
      ShowMotionPath: true
    Queue Size: 100
    Value: true
  - Class: rviz/Marker
    Enabled: true
    Marker Topic: /car
    Name: car
    Namespaces:
      car: true
    Queue Size: 100
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: base_map
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.200000003
    Style: Flat Squares
    Topic: /basemap_rgb
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: vector_map
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.200000003
    Style: Flat Squares
    Topic: /vector_map
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: Intensity
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: perception_cell
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.100000001
    Style: Flat Squares
    Topic: /perception/visulization/tpperception_cells
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: /perception/visulization/tpperception
    Name: perception_bbox
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Class: rviz/Marker
    Enabled: true
    Marker Topic: /map_collection_point
    Name: map_collection_point
    Namespaces:
      {}
    Queue Size: 20
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: Intensity
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 255
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: lidar_points
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.100000001
    Style: Flat Squares
    Topic: /lidar_points_2
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: mapengine_path
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.300000012
    Style: Flat Squares
    Topic: /mapengine_path
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: left_mapengine_path
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.150000006
    Style: Flat Squares
    Topic: /left_mapengine_path
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: right_mapengine_path
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.150000006
    Style: Flat Squares
    Topic: /right_mapengine_path
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: trajectory_marker_line
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.00999999978
    Style: Flat Squares
    Topic: /trajectory_marker_line
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Class: rviz/MarkerArray
    Enabled: false
    Marker Topic: trajectory_marker_text
    Name: trajectory_marker_text
    Namespaces:
      {}
    Queue Size: 100
    Value: false
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: objectfusion_marker
    Name: objectfusion_marker
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: objectfusion_bbox
    Name: objectfusion_bbox
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: objectfusion_marker_text
    Name: objectfusion_marker_text
    Namespaces:
      {}
    Queue Size: 100
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: RGB8
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: car_layout
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.100000001
    Style: Flat Squares
    Topic: /p_car_model
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: prediction_trajectory
    Name: prediction
    Namespaces:
      {}
    Queue Size: 100
    Value: true
Enabled: true
Global Options:
  Background Color: 48; 48; 48
  Default Light: true
  Fixed Frame: base_link
  Frame Rate: 30
Name: root
Tools:
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Topic: initialpose
  - Class: rviz/SetGoal
    Topic: goal
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Topic: initialpose
  - Class: rviz/SetGoal
    Topic: goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetInitialPose
    Topic: initialpose
  - Class: rviz/SetInitialPose
    Topic: initialpose
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
  - Class: rviz/SetGoal
    Topic: /move_base_simple/goal
Value: true
Views:
  Current:
    Class: rviz/ThirdPersonFollower
    Distance: 44.1473961
    Enable Stereo Rendering:
      Stereo Eye Separation: 0.0599999987
      Stereo Focal Distance: 1
      Swap Stereo Eyes: false
      Value: false
    Focal Point:
      X: 0.838410854
      Y: -6.68141222
      Z: 2.85586816e-06
    Focal Shape Fixed Size: true
    Focal Shape Size: 0.0500000007
    Invert Z Axis: false
    Name: Current View
    Near Clip Distance: 0.00999999978
    Pitch: 0.350398123
    Target Frame: <Fixed Frame>
    Value: ThirdPersonFollower (rviz)
    Yaw: 3.5753963
  Saved: ~
